# Generated by Django 5.1.1 on 2024-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('father_name', models.CharField(max_length=60)),
                ('mother_name', models.CharField(max_length=60)),
                ('address', models.TextField(max_length=255)),
                ('dob', models.DateField()),
                ('phone_no', models.IntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=255)),
            ],
        ),
    ]
