# Generated by Django 5.1.1 on 2024-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='img',
            field=models.ImageField(upload_to='student_img/'),
        ),
    ]
