# Generated by Django 5.1.1 on 2024-09-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_register_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Student_details',
        ),
    ]
