# Generated by Django 5.1.1 on 2024-10-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_first_name_student_details_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='first_name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_details',
            name='last_name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
