# Generated by Django 5.1.1 on 2024-10-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_student_details_first_name_student_details_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='last_name',
        ),
    ]
