# Generated by Django 5.1.1 on 2024-10-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_student_details_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='full_name',
        ),
    ]
