# Generated by Django 5.1.1 on 2024-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_student_details_adhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='adhar_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='fifth_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='first_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='first_year_tot_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='first_year_tot_per',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='forth_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='high_sc_per',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='second_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='second_year_tot_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='second_year_tot_per',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='sel_board',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='sexth_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_per',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='ubter_roll_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
