# Generated by Django 5.1.1 on 2024-10-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_student_details_adhar_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='sexth_sem_marks',
            new_name='sixth_sem_marks',
        ),
    ]
