# Generated by Django 5.1.1 on 2024-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_student_details_fifth_sem_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='fifth_sem_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='sixth_sem_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_per',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
