# Generated by Django 5.1.1 on 2024-10-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_student_details_fifth_sem_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='ubter_roll_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
