# Generated by Django 5.1.1 on 2024-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_student_details_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='img',
            field=models.ImageField(upload_to='student_img/'),
        ),
    ]
