# Generated by Django 5.1.1 on 2024-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_student_details_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='fifth_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='sixth_sem_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_per',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
