# Generated by Django 5.1.1 on 2024-10-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_student_details_gender_student_details_high_sc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='father_occupation',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='mother_occupation',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
