# Generated by Django 5.1.1 on 2024-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_student_details_father_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='fifth_sem_marks',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='first_sem_marks',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='first_year_tot_cgpa',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='first_year_tot_per',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='forth_sem_marks',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='high_sc_per',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='inter_per',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='second_sem_marks',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='second_year_tot_cgpa',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='second_year_tot_per',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='sixth_sem_marks',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_sem_marks',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_cgpa',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='third_year_tot_per',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
