# Generated by Django 5.1.1 on 2024-10-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_student_details_fifth_sem_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='ubter_roll_no',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
