# Generated by Django 5.1.1 on 2024-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_alter_student_details_ubter_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='passing_year',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
