# Generated by Django 5.1.1 on 2024-10-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_student_details_passing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='student_details',
            name='current_stu_address',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='permanent_stu_address',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
