# Generated by Django 5.1.1 on 2025-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_student_details_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='branch',
            field=models.CharField(max_length=60),
        ),
    ]
