# Generated by Django 5.1.1 on 2025-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_student_details_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=60)),
                ('news_discription', models.TimeField(max_length=260)),
            ],
        ),
    ]
