# Generated by Django 5.1.1 on 2025-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_news_management_news_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=60)),
                ('news_description', models.TextField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=60)),
                ('notice_description', models.TextField(max_length=260)),
            ],
        ),
        migrations.RenameField(
            model_name='news_management',
            old_name='news_discription',
            new_name='news_description',
        ),
    ]
