# Generated by Django 5.1.1 on 2025-02-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_event_management_notice_management_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_management',
            old_name='news_description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='event_management',
            old_name='news_title',
            new_name='event_title',
        ),
    ]
