# Generated by Django 5.1.1 on 2025-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_rename_news_description_event_management_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=12, unique=True)),
                ('about_me', models.CharField(max_length=400, null=True)),
                ('email', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=300, null=True)),
                ('projects', models.CharField(max_length=300, null=True)),
                ('certificates', models.CharField(max_length=300, null=True)),
                ('hobbies', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
