# Generated by Django 5.1.1 on 2025-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_cv_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=20)),
                ('gallery_img', models.ImageField(upload_to='gallery_img/')),
            ],
        ),
    ]
