# Generated by Django 5.1.1 on 2025-04-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_gallery_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_management',
            name='image_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
