# Generated by Django 5.1.1 on 2025-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_alter_gallery_management_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30, null=True)),
                ('staff_role', models.CharField(max_length=30, null=True)),
                ('gallery_img', models.ImageField(upload_to='staff_img/')),
            ],
        ),
    ]
