# Generated by Django 5.1.1 on 2025-05-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_staff_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_management',
            old_name='gallery_img',
            new_name='staff_img',
        ),
    ]
