from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.splesh_scr,name='splesh_scr'),
    path('home/',views.home,name='home'),
    path('staff/',views.staff,name='staff'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('student_teacher_logout/',views.student_teacher_logout,name='student_teacher_logout'),
    path('student',views.student,name='student'),
    path('student_cv/<roll>',views.student_cv,name='student_cv'),
    path('cv_form/<stu_roll>',views.cv_form,name='cv_form'),
    path('cv_update/<roll_no>',views.update_cv,name='update_cv'),
    path('cv_update_logic/<roll>',views.cv_update_logic,name='cv_update_logic'),
    path('student_view_page/',views.student_view_page,name='student_view_page'),
    path('progress_report/<stu_roll>',views.progress_report,name='progress_report'),
    path('teacher_register/',views.teacher_register,name='teacher_register'),
    path('teacher_login/',views.teacher_login,name='teacher_login'),
    path('teacher_view_page/<sel_b>/<branch_id>',views.teacher_view_page,name='teacher_view_page'),
    path('pdf/<branch_id>/<sel_b>',views.pdf,name='pdf'),
    path('stu_det_pdf/<roll_no>',views.stu_det_pdf,name='stu_det_pdf'),
    path('dashboard_student_data',views.dashboard_student_data,name='dashboard_student_data'),
    path('delete_user/<roll_no>/<branch_id>',views.delete_user,name='delete_user'),
    path('teacher_student_select/<branch_id>',views.teacher_student_select,name='teacher_student_select'),
    path('update_student_details/<roll_no>/<full_name>/<side>/<branch_id>/',views.update_student_details,name='update_student_details'),
    path('update/<id>/<side>/<branch_id>',views.update,name='update'),
    path('about_us/',views.about_us,name='about_us'),
    path('course_detail_cse/',views.course_detail_cse,name='course_detail_cse'),
    path('course_detail_it/',views.course_detail_it,name='course_detail_it'),
    path('gallery/',views.gallery,name='gallery'),
    path('addmission/',views.addmission,name='addmission'),
    path('books_page/',views.books_page,name='books_page'),
    path('admin_login/',views.admin_login,name='admin_login'),
    path('admin_panel/',views.admin_panel,name='admin_panel'),
    path('news_management/', views.news_management, name='news_management'),
    path('delete_news/<id>', views.delete_news, name='delete_news'),
    path('events_management/',views.event_management,name='event_management'),
    path('delete_event/<id>', views.delete_event, name='delete_event'),
    path('notice_management/',views.notice_management,name='notice_management'),
    path('delete_notice/<id>', views.delete_notice, name='delete_notice'),
    path('gallery_management/', views.gallery_management, name='gallery_management'),
    path('remove_gallery_img/<id>', views.remove_gallery_img, name='remove_gallery_img'),
    path('staff_management', views.staff_management, name='staff_management'),
    path('remove_staff_img/<id>', views.remove_staff_img, name='remove_staff_img'),
    path('chatbot/', views.chat_view, name='chatbot'),
    path('clear_chat_history/', views.clear_chat_history, name='clear_chat_history'),
]